export const genres = [
  "Pop",
  "Hip-Hop/Rap",
  "Dance",
  "Electronic",
  "R&B/Soul",
  "Alternative",
  "Rock",
  "Latin",
  "Film, TV & Stage",
  "Country",
  "AfroBeats",
  "Worldwide",
  "Reggae/Dancehall",
  "House",
  "K-Pop",
  "French Pop",
  "Singer/Songwriter",
  "Regional Mexicano",
];
